{{- if .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-httproute
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  {{- with .Values.httproute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostnames:
    {{- range .Values.httproute.hosts }}
    - "{{ .host }}"
    {{- end }}
  rules:
    {{- range .Values.httproute.hosts }}
    - matches:
        {{- range .paths }}
        - path:
            type: PathPrefix
            value: "{{ . }}"
        {{- end }}
      backendRefs:
        - name: {{ $.Release.Name }}-svc
          port: 80
    {{- end }}
{{- end }}
